<?php $this->headTitle()->prepend('Editar Usuário'); ?>

<?php
	//$this->title = "Editar";
	//echo $this->user['id'];
	//echo $this->form ;
?>

 <div class="span6">
            <div class="widget-content">
              <div class="widget-box">
                <form   id="usuario" enctype="application/x-www-form-urlencoded" class="form-horizontal well ucase" action"<?php echo $this->form->getAction() ?>" method="<?php echo $this->form->getMethod()?>">
				
                  <fieldset>
                    <legend>Editar Usuário</legend>
                    
                    <fieldset id="address-form">
                      <div class="control-group">
                        <label class="control-label">Login:</label>
                        <div class="controls">
					<?= $this->form->login ?></div>
					
                      </div>
                      <div class="control-group">
                        <label class="control-label">Nome Completo: </label>
                        <div class="controls">
                          <?= $this->form->nome_completo ?>
                        </div>
                      </div>
                      <div class="control-group">
                        <label class="control-label">Senha:</label>
                        <div class="controls">
                          <?= $this->form->senha ?>

                        </div>
                      </div>
                      <div class="control-group">
                      <label class="control-label">Tipo</label>
                      <div class="controls">
                        <label class="radio">
                         <?= $this->form->tipo ?>
                      
                          <p class="help-block"> <strong>Nota:</strong> Preencher todos os campos. </p>
                        </div>
                      </div>
                    </fieldset>
                  </fieldset>
                  <div class="form-actions">
                    <?= $this->form->submit ?>
                    <button type="submit" class="btn btn-info">Save changes</button>
                    <button class="btn btn-warning">Cancel</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
