<h3>Lista de usuários</h3>
<?php foreach($this->users as $user): ?>
<p><?php echo $user->login; ?></p>
<?php endforeach; ?>


<h3>Lista de Paciente</h3>
<?php foreach($this->pacientes as $paciente): ?>
<p><?php echo $paciente->nome_completo; ?></p>
<?php endforeach; ?>

<h3>Lista de Agendamento</h3>
<?php foreach($this->agendas as $agenda): ?>

<p>Nome:<?php echo $agenda->nome_professor; ?></p>

<?php endforeach; ?>

<p>Aluno: <?php echo $this->agenda_user->nome_completo; ?>, 
<p>Paciente: <?php echo $this->agenda_paciente->nome_completo; ?>, 
<p>Professor: <?php echo $this->nome_professor; ?>, 
<p>Data: <?php echo $this->data_agenda; ?>, 

