<div class="span6" style="width:720px;">
  <div class="widget-block">
    <div class="widget-head">
      <h5><i class="black-icons users"></i>Pacientes</h5>
      <div class="widget-control pull-right"> <a href="#" data-toggle="dropdown" class="btn dropdown-toggle"><i class="icon-cog"></i><b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="<?php echo $this->url(array('controller'=>'Paciente','action'=>'adicionar'),null,true);?>"><i class="icon-plus"></i> Criar novo paciente </a></li>
          <li><a href="#"><i class="icon-remove"></i> Remover paciente </a></li>
          <li><a href="#"><i class="icon-pencil"></i> Editar paciente </a></li>
        </ul>
      </div>
    </div>
    <div class="widget-content">
      <div class="widget-searchbox">
        <ul>
          <li class="row-counts"></li>
          <li class="right">
            <form action="#" method="get">
              <div class="input-prepend"> <span class="add-on"><i class="icon-search"></i></span>
                <input type="text" class="span2">
              </div>
            </form>
          </li>
        </ul>
      </div>
      <div class="widget-box">
        <table class="table user-tbl">
          <thead>
            <tr>
              <th class="center"> ID </th>
              <th class="center"> Nome </th>
              <th> Profissao </th>
              <th> Info </th>
            </tr>
          </thead>
          <tbody>
            <?php foreach($this->pacientes as $paciente) : ?>
            <tr>
              <td class="center"><?php echo $this->escape($paciente->id_paciente);?></td>
              <td class="center"><span class="user-position"><?php echo $this->escape($paciente->nome_completo);?></span></td>
              <td><strong><?php echo $this->escape($paciente->profissao);?></strong></td>
              <td><div class="btn-group pull-right" style=" float: center; ">
                  <button data-toggle="dropdown" class="btn dropdown-toggle"><i class="icon-cog"></i><span class="caret"></span></button>
                  <ul class="dropdown-menu">
                    <li><a href="<?php echo $this->url(array('controller'=>'Paciente','action'=>'minhaconta', 'id'=>$paciente->id_paciente),null,true );
                    ?>"><i class="icon-file"></i> Informacoes </a></li>
                    <li><a href="<?php echo $this->url(array('controller'=>'Paciente','action'=>'editar-conta', 'id'=>$paciente->id_paciente),null,true );
                    ?>"><i class="icon-edit"></i> Alterar paciente</a></li>
                    <li><a href="<?php echo $this->url(array('controller'=>'Paciente','action'=>'remover', 'id'=>$paciente->id_paciente),null,true );
                    ?>"><i class="icon-trash"></i> Remover Paciente</a></li>
                    <li class="divider"></li>
                  </ul>
                </div></td>
            </tr>
            <?php endforeach; ?>
          </tbody>
        </table>
      </div>
      <div class="widget-bottom">
        <div class="pagination">
          <ul>
            <li><a href="#">Prev</a></li>
            <li class="active"><a href="#">1</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><a href="#">Next</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>