<?php $this->headTitle()->prepend('informacoes'); ?>


<h2>ID: <?php echo $this->paciente ['id_paciente']; ?></h2>
<h2>Nome: <?php echo $this->paciente ['nome_completo']; ?></h2>
<h2>Profissao: <?php echo $this->paciente ['profissao']; ?></h2>	
<h2>Nacionalidade: <?php echo $this->paciente ['nacionalidade']; ?></h2>
<h2>Naturalidade: <?php echo $this->paciente ['naturalidade']; ?></h2>
<h2>Data de Nascimento: <?php echo $this->paciente ['data_nasc']; ?></h2>
<h2>Telefone Celular: <?php echo $this->paciente ['tel_cel']; ?></h2>
<h2>Telefone Residencial: <?php echo $this->paciente ['tel_fixo']; ?></h2>
<h2>Endereco: <?php echo $this->paciente ['logradouro']; ?></h2>
<h2>Numero: <?php echo $this->paciente ['numero']; ?></h2>
<h2>Complemento: <?php echo $this->paciente ['complemento']; ?></h2>
<h2>CEP: <?php echo $this->paciente ['cep']; ?></h2>
<h2>Bairro: <?php echo $this->paciente ['bairro']; ?></h2>
<h2>cidade: <?php echo $this->paciente ['cidade']; ?></h2>
<h2>estado: <?php echo $this->paciente ['estado']; ?></h2>

